[package]
name = "swot"
version = "0.0.1"
authors = ["Sean Cross <sean@xobs.io>"]
edition = "2018"
license = "Apache-2"

[dependencies]
ftdi-vcp-rs = { path = "ftdi-vcp-rs" }

[build-dependencies]
cc = { version = "1", features = ["parallel"] }
